# Form implementation generated from reading ui file 'unt.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_new_two_window(object):
    def setupUi(self, new_two_window):
        new_two_window.setObjectName("new_two_window")
        new_two_window.resize(680, 487)
        new_two_window.setMaximumSize(QtCore.QSize(700, 550))
        new_two_window.setSizeIncrement(QtCore.QSize(700, 550))
        self.tableWidget = QtWidgets.QTableWidget(parent=new_two_window)
        self.tableWidget.setGeometry(QtCore.QRect(40, 170, 591, 271))
        self.tableWidget.setSizeIncrement(QtCore.QSize(30, 40))
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(115)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(45)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.tableWidget.verticalHeader().setMinimumSectionSize(42)
        self.push_button = QtWidgets.QPushButton(parent=new_two_window)
        self.push_button.setGeometry(QtCore.QRect(50, 80, 181, 61))
        self.push_button.setObjectName("push_button")
        self.push_button_2 = QtWidgets.QPushButton(parent=new_two_window)
        self.push_button_2.setGeometry(QtCore.QRect(425, 80, 181, 61))
        self.push_button_2.setObjectName("push_button_2")

        self.retranslateUi(new_two_window)
        QtCore.QMetaObject.connectSlotsByName(new_two_window)

    def retranslateUi(self, new_two_window):
        _translate = QtCore.QCoreApplication.translate
        new_two_window.setWindowTitle(_translate("new_two_window", "Form"))
        self.push_button.setText(_translate("new_two_window", "Добавить"))
        self.push_button_2.setText(_translate("new_two_window", "Изменить"))
